eureka:
  client:
    #  use boolean false so that eureka client should not register by itself, it is a server and should not behave like a client
    register-with-eureka: false
    #other client will fetch registry & we don't want to fetch registry for server
    fetch-registry: false
  instance:
    hostname: localhost
server:
  port: 8761

